### ISSUE TITLE
Pratica 1 - GitHub Issues - Convidando colaboradores

### ISSUE THREAD

**Issue by rodrigolsouza** [rodrigolsouza/GCMS-Rodrigo-Souza.#1]
Caro professor Ramide Dantas (@ramidedantas), o senhor poderia compor minha lista de colaboradores no projeto para a disciplina GCMS ?
Aqui segue o link da lista de colaboradores: 
[README](https://github.com/rodrigolsouza/GCMS-Rodrigo-Souza./blob/master/README.md)

**Comment by ramidedantas** [comment]
@rodrigolsouza nome adicionado, pode fechar chamado.
